#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoPrintingUtility.DA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="ExPost")]
	public partial class ExPostDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public ExPostDataContext() : 
				base(global::MemoPrintingUtility.DA.Properties.Settings.Default.ExPostConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ExPostDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExPostDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExPostDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ExPostDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsertSubjectRangeCodeYear")]
		public int InsertSubjectRangeCodeYear([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string subjectCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(200)")] string subjectName, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="CourseName", DbType="VarChar(100)")] string courseName, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> year, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Course", DbType="Int")] System.Nullable<int> course, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Count", DbType="Int")] System.Nullable<int> count, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RangeFrom", DbType="Int")] System.Nullable<int> rangeFrom, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RangEnd", DbType="Int")] System.Nullable<int> rangEnd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subjectCode, subjectName, courseName, year, course, count, rangeFrom, rangEnd);
			return ((int)(result.ReturnValue));
		}
	}
}
#pragma warning restore 1591
