<?xml version="1.0" encoding="utf-8"?><Database Name="kupost" Class="KUPostDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=14.139.85.68,3339;Initial Catalog=kupost;User ID=sa" SettingsObjectName="MemoPrintingUtility.DA.Properties.Settings" SettingsPropertyName="kupostConnectionString1" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_GetSDLCConData_TRReport" Method="sp_GetSDLCConData_TRReport">
    <Parameter Name="Course" Parameter="course" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_GetSDLCConData_TRReportResult">
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HTNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P11" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P12" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P13" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P14" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P15" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P16" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P21" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P22" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P23" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P24" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P25" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P26" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P27" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P31" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P32" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P33" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P34" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P35" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P36" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P37" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M11" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y11" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M12" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y12" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M13" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y13" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M14" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y14" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M15" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y15" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M16" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y16" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M21" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y21" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M22" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y22" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M23" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y23" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M24" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y24" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M25" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y25" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M26" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y26" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M27" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y27" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M31" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y31" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M32" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y32" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M33" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y33" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M34" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y34" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M35" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y35" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M36" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y36" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M37" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y37" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="YR1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="YR2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="YR3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PRT1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PRTA1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PRT2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PRTA2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TOT1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TOT2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DEAFDUM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetSDLCResultData_TRReport" Method="sp_GetSDLCResultData_TRReport">
    <Parameter Name="Course" Parameter="course" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_GetSDLCResultData_TRReportResult">
      <Column Name="CRS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FK_YEAR" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FK_CLGCODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CLM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HTNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONS_SUB" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SUBJECTNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CC_FINAL_VALMARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RESULT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TOTAL_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FINALRES" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FNAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sts" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_insertSubjectRangeCode" Method="SP_insertSubjectRangeCode">
    <Parameter Name="SubJectCode" Parameter="subJectCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="count" Type="System.Int32" DbType="Int" />
    <Parameter Name="RangeForm" Parameter="rangeForm" Type="System.Int32" DbType="Int" />
    <Parameter Name="RangeEnd" Parameter="rangeEnd" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>