<?xml version="1.0" encoding="utf-8"?><Database Name="kupost" Class="KUPostDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=14.139.85.68,3339;Initial Catalog=kupost;User ID=sa" SettingsObjectName="MemoPrintingUtility.DA.Properties.Settings" SettingsPropertyName="kupostConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.sp_GetSDLCConData_TRReport" Method="sp_GetSDLCConData_TRReport">
    <Parameter Name="Course" Parameter="course" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_GetSDLCConData_TRReportResult">
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HTNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P11" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P12" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P13" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P14" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P15" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P16" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P21" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P22" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P23" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P24" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P25" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P26" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P27" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P31" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P32" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P33" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P34" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P35" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P36" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P37" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M11" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y11" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M12" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y12" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M13" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y13" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M14" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y14" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M15" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y15" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M16" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y16" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M21" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y21" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M22" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y22" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M23" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y23" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M24" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y24" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M25" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y25" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M26" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y26" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M27" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y27" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M31" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y31" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M32" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y32" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M33" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y33" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M34" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y34" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M35" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y35" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M36" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y36" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M37" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Y37" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="YR1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="YR2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="YR3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PRT1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PRTA1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PRT2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="PRTA2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TOT1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TOT2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="DEAFDUM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.sp_GetSDLCResultData_TRReport" Method="sp_GetSDLCResultData_TRReport">
    <Parameter Name="Course" Parameter="course" Type="System.String" DbType="VarChar(20)" />
    <ElementType Name="sp_GetSDLCResultData_TRReportResult">
      <Column Name="CRS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FK_YEAR" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TP" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FK_CLGCODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CLM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HTNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONS_SUB" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SUBJECTNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CC_FINAL_VALMARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RESULT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TOTAL_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FINALRES" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="NAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="FNAME" Type="System.String" DbType="VarChar(500)" CanBeNull="true" />
      <Column Name="GENDER" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="sts" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllSubjectDeails" Method="GetAllSubjectDeails">
    <ElementType Name="GetAllSubjectDeailsResult">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="FK_YEAR" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FK_SEM" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FK_COURSEID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FK_BRANCHID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="FK_SUBJECTID" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SHORTCODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SUBJECTNAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ALIASNAME" Type="System.String" DbType="VarChar(255)" CanBeNull="true" />
      <Column Name="ISINTERNAL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ISPRACTICAL" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="PRAC_SUBCODE" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="ISCBCS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="[ORDER]" Member="ORDER" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="STATUS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="MAXINTMARKS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MAXPRACTICALMARKS" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="MAXINTSESSMARKS" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="WEF" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAGE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PATTERN" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="CREATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="UPDATED_DATE" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CREATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="UPDATED_BY" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetAllCourses" Method="GetAllCourses">
    <ElementType Name="GetAllCoursesResult">
      <Column Name="Pk_CourseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="subbranch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="enexam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="years" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="months" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_papers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="theory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="practical" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="course_pattern" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="university" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="college" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="shortname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="max_years" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="max_months" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="course_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cycle_exists" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cycle1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cycle2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="markssheet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="attempts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cutof_attendance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="grace_attendance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="leet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartRollNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndRollNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_mid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAGE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createddate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updateddate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="createdby" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="updatedby" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_insertSubjectRangeCode" Method="SP_insertSubjectRangeCode">
    <Parameter Name="SubJectCode" Parameter="subJectCode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="count" Type="System.Int32" DbType="Int" />
    <Parameter Name="Year" Parameter="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="Sem" Parameter="sem" Type="System.Int32" DbType="Int" />
    <Parameter Name="course" Type="System.Int32" DbType="Int" />
    <Parameter Name="CourseName" Parameter="courseName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="SubjectName" Parameter="subjectName" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="RangeForm" Parameter="rangeForm" Type="System.Int32" DbType="Int" />
    <Parameter Name="RangeEnd" Parameter="rangeEnd" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_GetAllYrSubjectDetails" Method="SP_GetAllYrSubjectDetails">
    <ElementType Name="SP_GetAllYrSubjectDetailsResult">
      <Column Name="Pk_CourseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="fk_sem" Type="System.Decimal" DbType="Decimal(18,0)" CanBeNull="true" />
      <Column Name="ShortName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="SubjectName" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>