#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoPrintingUtility.DA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kupost")]
	public partial class KUPostDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public KUPostDBDataContext() : 
				base(global::MemoPrintingUtility.DA.Properties.Settings.Default.kupostConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public KUPostDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KUPostDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KUPostDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public KUPostDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetSDLCConData_TRReport")]
		public ISingleResult<sp_GetSDLCConData_TRReportResult> sp_GetSDLCConData_TRReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Course", DbType="VarChar(20)")] string course)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course);
			return ((ISingleResult<sp_GetSDLCConData_TRReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.sp_GetSDLCResultData_TRReport")]
		public ISingleResult<sp_GetSDLCResultData_TRReportResult> sp_GetSDLCResultData_TRReport([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Course", DbType="VarChar(20)")] string course)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course);
			return ((ISingleResult<sp_GetSDLCResultData_TRReportResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_insertSubjectRangeCode")]
		public int SP_insertSubjectRangeCode([global::System.Data.Linq.Mapping.ParameterAttribute(Name="SubJectCode", DbType="VarChar(20)")] string subJectCode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> count, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RangeForm", DbType="Int")] System.Nullable<int> rangeForm, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="RangeEnd", DbType="Int")] System.Nullable<int> rangeEnd)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), subJectCode, count, rangeForm, rangeEnd);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class sp_GetSDLCConData_TRReportResult
	{
		
		private string _CODE;
		
		private string _HTNO;
		
		private string _P11;
		
		private string _P12;
		
		private string _P13;
		
		private string _P14;
		
		private string _P15;
		
		private string _P16;
		
		private string _P21;
		
		private string _P22;
		
		private string _P23;
		
		private string _P24;
		
		private string _P25;
		
		private string _P26;
		
		private string _P27;
		
		private string _P31;
		
		private string _P32;
		
		private string _P33;
		
		private string _P34;
		
		private string _P35;
		
		private string _P36;
		
		private string _P37;
		
		private string _M11;
		
		private string _Y11;
		
		private string _M12;
		
		private string _Y12;
		
		private string _M13;
		
		private string _Y13;
		
		private string _M14;
		
		private string _Y14;
		
		private string _M15;
		
		private string _Y15;
		
		private string _M16;
		
		private string _Y16;
		
		private string _M21;
		
		private string _Y21;
		
		private string _M22;
		
		private string _Y22;
		
		private string _M23;
		
		private string _Y23;
		
		private string _M24;
		
		private string _Y24;
		
		private string _M25;
		
		private string _Y25;
		
		private string _M26;
		
		private string _Y26;
		
		private string _M27;
		
		private string _Y27;
		
		private string _M31;
		
		private string _Y31;
		
		private string _M32;
		
		private string _Y32;
		
		private string _M33;
		
		private string _Y33;
		
		private string _M34;
		
		private string _Y34;
		
		private string _M35;
		
		private string _Y35;
		
		private string _M36;
		
		private string _Y36;
		
		private string _M37;
		
		private string _Y37;
		
		private string _YR1;
		
		private string _YR2;
		
		private string _YR3;
		
		private string _PRT1;
		
		private string _PRTA1;
		
		private string _PRT2;
		
		private string _PRTA2;
		
		private string _TOT1;
		
		private string _TOT2;
		
		private string _DEAFDUM;
		
		public sp_GetSDLCConData_TRReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(255)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTNO", DbType="NVarChar(255)")]
		public string HTNO
		{
			get
			{
				return this._HTNO;
			}
			set
			{
				if ((this._HTNO != value))
				{
					this._HTNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P11", DbType="NVarChar(255)")]
		public string P11
		{
			get
			{
				return this._P11;
			}
			set
			{
				if ((this._P11 != value))
				{
					this._P11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P12", DbType="NVarChar(255)")]
		public string P12
		{
			get
			{
				return this._P12;
			}
			set
			{
				if ((this._P12 != value))
				{
					this._P12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P13", DbType="NVarChar(255)")]
		public string P13
		{
			get
			{
				return this._P13;
			}
			set
			{
				if ((this._P13 != value))
				{
					this._P13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P14", DbType="NVarChar(255)")]
		public string P14
		{
			get
			{
				return this._P14;
			}
			set
			{
				if ((this._P14 != value))
				{
					this._P14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P15", DbType="NVarChar(255)")]
		public string P15
		{
			get
			{
				return this._P15;
			}
			set
			{
				if ((this._P15 != value))
				{
					this._P15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P16", DbType="NVarChar(255)")]
		public string P16
		{
			get
			{
				return this._P16;
			}
			set
			{
				if ((this._P16 != value))
				{
					this._P16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P21", DbType="NVarChar(255)")]
		public string P21
		{
			get
			{
				return this._P21;
			}
			set
			{
				if ((this._P21 != value))
				{
					this._P21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P22", DbType="NVarChar(255)")]
		public string P22
		{
			get
			{
				return this._P22;
			}
			set
			{
				if ((this._P22 != value))
				{
					this._P22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P23", DbType="NVarChar(255)")]
		public string P23
		{
			get
			{
				return this._P23;
			}
			set
			{
				if ((this._P23 != value))
				{
					this._P23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P24", DbType="NVarChar(255)")]
		public string P24
		{
			get
			{
				return this._P24;
			}
			set
			{
				if ((this._P24 != value))
				{
					this._P24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P25", DbType="NVarChar(255)")]
		public string P25
		{
			get
			{
				return this._P25;
			}
			set
			{
				if ((this._P25 != value))
				{
					this._P25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P26", DbType="NVarChar(255)")]
		public string P26
		{
			get
			{
				return this._P26;
			}
			set
			{
				if ((this._P26 != value))
				{
					this._P26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P27", DbType="NVarChar(255)")]
		public string P27
		{
			get
			{
				return this._P27;
			}
			set
			{
				if ((this._P27 != value))
				{
					this._P27 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P31", DbType="NVarChar(255)")]
		public string P31
		{
			get
			{
				return this._P31;
			}
			set
			{
				if ((this._P31 != value))
				{
					this._P31 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P32", DbType="NVarChar(255)")]
		public string P32
		{
			get
			{
				return this._P32;
			}
			set
			{
				if ((this._P32 != value))
				{
					this._P32 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P33", DbType="NVarChar(255)")]
		public string P33
		{
			get
			{
				return this._P33;
			}
			set
			{
				if ((this._P33 != value))
				{
					this._P33 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P34", DbType="NVarChar(255)")]
		public string P34
		{
			get
			{
				return this._P34;
			}
			set
			{
				if ((this._P34 != value))
				{
					this._P34 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P35", DbType="NVarChar(255)")]
		public string P35
		{
			get
			{
				return this._P35;
			}
			set
			{
				if ((this._P35 != value))
				{
					this._P35 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P36", DbType="NVarChar(255)")]
		public string P36
		{
			get
			{
				return this._P36;
			}
			set
			{
				if ((this._P36 != value))
				{
					this._P36 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P37", DbType="NVarChar(255)")]
		public string P37
		{
			get
			{
				return this._P37;
			}
			set
			{
				if ((this._P37 != value))
				{
					this._P37 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M11", DbType="NVarChar(255)")]
		public string M11
		{
			get
			{
				return this._M11;
			}
			set
			{
				if ((this._M11 != value))
				{
					this._M11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y11", DbType="NVarChar(255)")]
		public string Y11
		{
			get
			{
				return this._Y11;
			}
			set
			{
				if ((this._Y11 != value))
				{
					this._Y11 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M12", DbType="NVarChar(255)")]
		public string M12
		{
			get
			{
				return this._M12;
			}
			set
			{
				if ((this._M12 != value))
				{
					this._M12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y12", DbType="NVarChar(255)")]
		public string Y12
		{
			get
			{
				return this._Y12;
			}
			set
			{
				if ((this._Y12 != value))
				{
					this._Y12 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M13", DbType="NVarChar(255)")]
		public string M13
		{
			get
			{
				return this._M13;
			}
			set
			{
				if ((this._M13 != value))
				{
					this._M13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y13", DbType="NVarChar(255)")]
		public string Y13
		{
			get
			{
				return this._Y13;
			}
			set
			{
				if ((this._Y13 != value))
				{
					this._Y13 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M14", DbType="NVarChar(255)")]
		public string M14
		{
			get
			{
				return this._M14;
			}
			set
			{
				if ((this._M14 != value))
				{
					this._M14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y14", DbType="NVarChar(255)")]
		public string Y14
		{
			get
			{
				return this._Y14;
			}
			set
			{
				if ((this._Y14 != value))
				{
					this._Y14 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M15", DbType="NVarChar(255)")]
		public string M15
		{
			get
			{
				return this._M15;
			}
			set
			{
				if ((this._M15 != value))
				{
					this._M15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y15", DbType="NVarChar(255)")]
		public string Y15
		{
			get
			{
				return this._Y15;
			}
			set
			{
				if ((this._Y15 != value))
				{
					this._Y15 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M16", DbType="NVarChar(255)")]
		public string M16
		{
			get
			{
				return this._M16;
			}
			set
			{
				if ((this._M16 != value))
				{
					this._M16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y16", DbType="NVarChar(255)")]
		public string Y16
		{
			get
			{
				return this._Y16;
			}
			set
			{
				if ((this._Y16 != value))
				{
					this._Y16 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M21", DbType="NVarChar(255)")]
		public string M21
		{
			get
			{
				return this._M21;
			}
			set
			{
				if ((this._M21 != value))
				{
					this._M21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y21", DbType="NVarChar(255)")]
		public string Y21
		{
			get
			{
				return this._Y21;
			}
			set
			{
				if ((this._Y21 != value))
				{
					this._Y21 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M22", DbType="NVarChar(255)")]
		public string M22
		{
			get
			{
				return this._M22;
			}
			set
			{
				if ((this._M22 != value))
				{
					this._M22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y22", DbType="NVarChar(255)")]
		public string Y22
		{
			get
			{
				return this._Y22;
			}
			set
			{
				if ((this._Y22 != value))
				{
					this._Y22 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M23", DbType="NVarChar(255)")]
		public string M23
		{
			get
			{
				return this._M23;
			}
			set
			{
				if ((this._M23 != value))
				{
					this._M23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y23", DbType="NVarChar(255)")]
		public string Y23
		{
			get
			{
				return this._Y23;
			}
			set
			{
				if ((this._Y23 != value))
				{
					this._Y23 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M24", DbType="NVarChar(255)")]
		public string M24
		{
			get
			{
				return this._M24;
			}
			set
			{
				if ((this._M24 != value))
				{
					this._M24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y24", DbType="NVarChar(255)")]
		public string Y24
		{
			get
			{
				return this._Y24;
			}
			set
			{
				if ((this._Y24 != value))
				{
					this._Y24 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M25", DbType="NVarChar(255)")]
		public string M25
		{
			get
			{
				return this._M25;
			}
			set
			{
				if ((this._M25 != value))
				{
					this._M25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y25", DbType="NVarChar(255)")]
		public string Y25
		{
			get
			{
				return this._Y25;
			}
			set
			{
				if ((this._Y25 != value))
				{
					this._Y25 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M26", DbType="NVarChar(255)")]
		public string M26
		{
			get
			{
				return this._M26;
			}
			set
			{
				if ((this._M26 != value))
				{
					this._M26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y26", DbType="NVarChar(255)")]
		public string Y26
		{
			get
			{
				return this._Y26;
			}
			set
			{
				if ((this._Y26 != value))
				{
					this._Y26 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M27", DbType="NVarChar(255)")]
		public string M27
		{
			get
			{
				return this._M27;
			}
			set
			{
				if ((this._M27 != value))
				{
					this._M27 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y27", DbType="NVarChar(255)")]
		public string Y27
		{
			get
			{
				return this._Y27;
			}
			set
			{
				if ((this._Y27 != value))
				{
					this._Y27 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M31", DbType="NVarChar(255)")]
		public string M31
		{
			get
			{
				return this._M31;
			}
			set
			{
				if ((this._M31 != value))
				{
					this._M31 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y31", DbType="NVarChar(255)")]
		public string Y31
		{
			get
			{
				return this._Y31;
			}
			set
			{
				if ((this._Y31 != value))
				{
					this._Y31 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M32", DbType="NVarChar(255)")]
		public string M32
		{
			get
			{
				return this._M32;
			}
			set
			{
				if ((this._M32 != value))
				{
					this._M32 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y32", DbType="NVarChar(255)")]
		public string Y32
		{
			get
			{
				return this._Y32;
			}
			set
			{
				if ((this._Y32 != value))
				{
					this._Y32 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M33", DbType="NVarChar(255)")]
		public string M33
		{
			get
			{
				return this._M33;
			}
			set
			{
				if ((this._M33 != value))
				{
					this._M33 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y33", DbType="NVarChar(255)")]
		public string Y33
		{
			get
			{
				return this._Y33;
			}
			set
			{
				if ((this._Y33 != value))
				{
					this._Y33 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M34", DbType="NVarChar(255)")]
		public string M34
		{
			get
			{
				return this._M34;
			}
			set
			{
				if ((this._M34 != value))
				{
					this._M34 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y34", DbType="NVarChar(255)")]
		public string Y34
		{
			get
			{
				return this._Y34;
			}
			set
			{
				if ((this._Y34 != value))
				{
					this._Y34 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M35", DbType="NVarChar(255)")]
		public string M35
		{
			get
			{
				return this._M35;
			}
			set
			{
				if ((this._M35 != value))
				{
					this._M35 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y35", DbType="NVarChar(255)")]
		public string Y35
		{
			get
			{
				return this._Y35;
			}
			set
			{
				if ((this._Y35 != value))
				{
					this._Y35 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M36", DbType="NVarChar(255)")]
		public string M36
		{
			get
			{
				return this._M36;
			}
			set
			{
				if ((this._M36 != value))
				{
					this._M36 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y36", DbType="NVarChar(255)")]
		public string Y36
		{
			get
			{
				return this._Y36;
			}
			set
			{
				if ((this._Y36 != value))
				{
					this._Y36 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M37", DbType="NVarChar(255)")]
		public string M37
		{
			get
			{
				return this._M37;
			}
			set
			{
				if ((this._M37 != value))
				{
					this._M37 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Y37", DbType="NVarChar(255)")]
		public string Y37
		{
			get
			{
				return this._Y37;
			}
			set
			{
				if ((this._Y37 != value))
				{
					this._Y37 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YR1", DbType="NVarChar(255)")]
		public string YR1
		{
			get
			{
				return this._YR1;
			}
			set
			{
				if ((this._YR1 != value))
				{
					this._YR1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YR2", DbType="NVarChar(255)")]
		public string YR2
		{
			get
			{
				return this._YR2;
			}
			set
			{
				if ((this._YR2 != value))
				{
					this._YR2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YR3", DbType="NVarChar(255)")]
		public string YR3
		{
			get
			{
				return this._YR3;
			}
			set
			{
				if ((this._YR3 != value))
				{
					this._YR3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRT1", DbType="NVarChar(255)")]
		public string PRT1
		{
			get
			{
				return this._PRT1;
			}
			set
			{
				if ((this._PRT1 != value))
				{
					this._PRT1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRTA1", DbType="NVarChar(255)")]
		public string PRTA1
		{
			get
			{
				return this._PRTA1;
			}
			set
			{
				if ((this._PRTA1 != value))
				{
					this._PRTA1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRT2", DbType="NVarChar(255)")]
		public string PRT2
		{
			get
			{
				return this._PRT2;
			}
			set
			{
				if ((this._PRT2 != value))
				{
					this._PRT2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PRTA2", DbType="NVarChar(255)")]
		public string PRTA2
		{
			get
			{
				return this._PRTA2;
			}
			set
			{
				if ((this._PRTA2 != value))
				{
					this._PRTA2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOT1", DbType="NVarChar(255)")]
		public string TOT1
		{
			get
			{
				return this._TOT1;
			}
			set
			{
				if ((this._TOT1 != value))
				{
					this._TOT1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOT2", DbType="NVarChar(255)")]
		public string TOT2
		{
			get
			{
				return this._TOT2;
			}
			set
			{
				if ((this._TOT2 != value))
				{
					this._TOT2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DEAFDUM", DbType="NVarChar(255)")]
		public string DEAFDUM
		{
			get
			{
				return this._DEAFDUM;
			}
			set
			{
				if ((this._DEAFDUM != value))
				{
					this._DEAFDUM = value;
				}
			}
		}
	}
	
	public partial class sp_GetSDLCResultData_TRReportResult
	{
		
		private string _CRS;
		
		private string _FK_YEAR;
		
		private string _EI;
		
		private string _TP;
		
		private string _FK_CLGCODE;
		
		private string _CLM;
		
		private string _HTNO;
		
		private string _CONS_SUB;
		
		private string _SUBJECTNAME;
		
		private string _CC_FINAL_VALMARKS;
		
		private string _RESULT;
		
		private string _TOTAL_MARKS;
		
		private string _FINALRES;
		
		private string _NAME;
		
		private string _FNAME;
		
		private string _GENDER;
		
		private string _sts;
		
		public sp_GetSDLCResultData_TRReportResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CRS", DbType="NVarChar(255)")]
		public string CRS
		{
			get
			{
				return this._CRS;
			}
			set
			{
				if ((this._CRS != value))
				{
					this._CRS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_YEAR", DbType="NVarChar(255)")]
		public string FK_YEAR
		{
			get
			{
				return this._FK_YEAR;
			}
			set
			{
				if ((this._FK_YEAR != value))
				{
					this._FK_YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EI", DbType="NVarChar(255)")]
		public string EI
		{
			get
			{
				return this._EI;
			}
			set
			{
				if ((this._EI != value))
				{
					this._EI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TP", DbType="NVarChar(255)")]
		public string TP
		{
			get
			{
				return this._TP;
			}
			set
			{
				if ((this._TP != value))
				{
					this._TP = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_CLGCODE", DbType="NVarChar(255)")]
		public string FK_CLGCODE
		{
			get
			{
				return this._FK_CLGCODE;
			}
			set
			{
				if ((this._FK_CLGCODE != value))
				{
					this._FK_CLGCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CLM", DbType="NVarChar(255)")]
		public string CLM
		{
			get
			{
				return this._CLM;
			}
			set
			{
				if ((this._CLM != value))
				{
					this._CLM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTNO", DbType="NVarChar(255)")]
		public string HTNO
		{
			get
			{
				return this._HTNO;
			}
			set
			{
				if ((this._HTNO != value))
				{
					this._HTNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONS_SUB", DbType="NVarChar(255)")]
		public string CONS_SUB
		{
			get
			{
				return this._CONS_SUB;
			}
			set
			{
				if ((this._CONS_SUB != value))
				{
					this._CONS_SUB = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBJECTNAME", DbType="NVarChar(255)")]
		public string SUBJECTNAME
		{
			get
			{
				return this._SUBJECTNAME;
			}
			set
			{
				if ((this._SUBJECTNAME != value))
				{
					this._SUBJECTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CC_FINAL_VALMARKS", DbType="NVarChar(255)")]
		public string CC_FINAL_VALMARKS
		{
			get
			{
				return this._CC_FINAL_VALMARKS;
			}
			set
			{
				if ((this._CC_FINAL_VALMARKS != value))
				{
					this._CC_FINAL_VALMARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESULT", DbType="NVarChar(255)")]
		public string RESULT
		{
			get
			{
				return this._RESULT;
			}
			set
			{
				if ((this._RESULT != value))
				{
					this._RESULT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TOTAL_MARKS", DbType="NVarChar(255)")]
		public string TOTAL_MARKS
		{
			get
			{
				return this._TOTAL_MARKS;
			}
			set
			{
				if ((this._TOTAL_MARKS != value))
				{
					this._TOTAL_MARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINALRES", DbType="NVarChar(255)")]
		public string FINALRES
		{
			get
			{
				return this._FINALRES;
			}
			set
			{
				if ((this._FINALRES != value))
				{
					this._FINALRES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NAME", DbType="VarChar(500)")]
		public string NAME
		{
			get
			{
				return this._NAME;
			}
			set
			{
				if ((this._NAME != value))
				{
					this._NAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNAME", DbType="VarChar(500)")]
		public string FNAME
		{
			get
			{
				return this._FNAME;
			}
			set
			{
				if ((this._FNAME != value))
				{
					this._FNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GENDER", DbType="VarChar(50)")]
		public string GENDER
		{
			get
			{
				return this._GENDER;
			}
			set
			{
				if ((this._GENDER != value))
				{
					this._GENDER = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sts", DbType="VarChar(50)")]
		public string sts
		{
			get
			{
				return this._sts;
			}
			set
			{
				if ((this._sts != value))
				{
					this._sts = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
