<?xml version="1.0" encoding="utf-8"?><Database Name="kudevdb" Class="MemoPrintDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=tcp:kudevelopment.database.windows.net;Initial Catalog=kudevdb;Persist Security Info=True;User ID=kudev2019" SettingsObjectName="MemoPrintingUtility.DA.Properties.Settings" SettingsPropertyName="kudevdbConnectionString" Provider="System.Data.SqlClient" />
  <Function Name="dbo.PR_COURSE_SELECT" Method="PR_COURSE_SELECT">
    <Parameter Name="STATUS" Parameter="sTATUS" Type="System.Int32" DbType="Int" />
    <Parameter Name="SEARCHVALUE" Parameter="sEARCHVALUE" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="COURSE_TYPE" Parameter="cOURSE_TYPE" Type="System.Int32" DbType="Int" />
    <ElementType Name="PR_COURSE_SELECTResult">
      <Column Name="Pk_CourseID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="CourseName" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="subbranch" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="enexam" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="sem" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="years" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="months" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="total_papers" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="theory" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="practical" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="category" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="course_pattern" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="university" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="college" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="description" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Column Name="shortname" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="max_years" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="max_months" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="course_type" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cycle_exists" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cycle1" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="cycle2" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="markssheet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="attempts" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="cutof_attendance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="grace_attendance" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="leet" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartRollNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="EndRollNo" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Status" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ur_mid" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PAGE_ID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="createddate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="updateddate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="createdby" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="updatedby" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_GetStudentDetails" Method="SP_GetStudentDetails">
    <Parameter Name="Course" Parameter="course" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Semister" Parameter="semister" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="Sem" Parameter="sem" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_GetStudentDetailsResult">
      <Column Name="FK_CLGCODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HTNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FULLNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FK_YEAR" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FK_SEM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ORD" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONVERT_SUBCODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SUBJECTNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CREDITS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VAL_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="INT_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MOD1_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MOD2_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GRACE_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GRACE_MARKS2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FINAL_VAL_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GRADEPOINT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LETERGRADE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RESULT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FINALRESULT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SGPA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.get_ConsDataforTR" Method="get_ConsDataforTR">
    <Parameter Name="Course" Parameter="course" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Semister" Parameter="semister" Type="System.Int32" DbType="Int" />
    <ElementType Name="get_ConsDataforTRResult">
      <Column Name="CODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HTNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SEM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A1" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A3" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A4" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P5" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M5" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S5" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R5" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A5" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P6" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M6" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S6" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R6" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A6" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P7" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M7" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S7" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R7" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A7" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P8" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M8" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S8" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R8" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A8" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P9" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M9" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S9" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R9" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A9" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="P10" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="M10" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="S10" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="R10" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="A10" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RES" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SGPA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EXAMMONT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.SP_MallPracDetails" Method="SP_MallPracDetails">
    <Parameter Name="Course" Parameter="course" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Semister" Parameter="semister" Type="System.Int32" DbType="Int" />
    <Parameter Name="year" Type="System.Int32" DbType="Int" />
    <Parameter Name="Sem" Parameter="sem" Type="System.Int32" DbType="Int" />
    <ElementType Name="SP_MallPracDetailsResult">
      <Column Name="FK_CLGCODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="HTNO" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FULLNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FK_YEAR" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FK_SEM" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="ORD" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EI" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CONVERT_SUBCODE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SUBJECTNAME" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CREDITS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="VAL_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="INT_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MOD1_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="MOD2_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GRACE_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GRACE_MARKS2" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FINAL_VAL_MARKS" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="GRADEPOINT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="LETERGRADE" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="RESULT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="FINALRESULT" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="SGPA" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>