#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoPrintingUtility.DA
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="kudevdb")]
	public partial class MemoPrintDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public MemoPrintDBDataContext() : 
				base(global::MemoPrintingUtility.DA.Properties.Settings.Default.kudevdbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MemoPrintDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MemoPrintDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MemoPrintDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MemoPrintDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.PR_COURSE_SELECT")]
		public ISingleResult<PR_COURSE_SELECTResult> PR_COURSE_SELECT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="STATUS", DbType="Int")] System.Nullable<int> sTATUS, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="SEARCHVALUE", DbType="VarChar(50)")] string sEARCHVALUE, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="COURSE_TYPE", DbType="Int")] System.Nullable<int> cOURSE_TYPE)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), sTATUS, sEARCHVALUE, cOURSE_TYPE);
			return ((ISingleResult<PR_COURSE_SELECTResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_GetStudentDetails")]
		public ISingleResult<SP_GetStudentDetailsResult> SP_GetStudentDetails([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Course", DbType="VarChar(50)")] string course, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Semister", DbType="Int")] System.Nullable<int> semister, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> year, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Sem", DbType="Int")] System.Nullable<int> sem)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course, semister, year, sem);
			return ((ISingleResult<SP_GetStudentDetailsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.get_ConsDataforTR")]
		public ISingleResult<get_ConsDataforTRResult> get_ConsDataforTR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Course", DbType="VarChar(50)")] string course, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="Semister", DbType="Int")] System.Nullable<int> semister)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), course, semister);
			return ((ISingleResult<get_ConsDataforTRResult>)(result.ReturnValue));
		}
	}
	
	public partial class PR_COURSE_SELECTResult
	{
		
		private int _Pk_CourseID;
		
		private string _CourseName;
		
		private System.Nullable<int> _subbranch;
		
		private System.Nullable<int> _enexam;
		
		private System.Nullable<int> _sem;
		
		private System.Nullable<int> _years;
		
		private System.Nullable<int> _months;
		
		private System.Nullable<int> _total_papers;
		
		private System.Nullable<int> _theory;
		
		private System.Nullable<int> _practical;
		
		private System.Nullable<int> _category;
		
		private System.Nullable<int> _course_pattern;
		
		private System.Nullable<int> _credit;
		
		private System.Nullable<int> _university;
		
		private System.Nullable<int> _college;
		
		private string _description;
		
		private string _shortname;
		
		private System.Nullable<int> _max_years;
		
		private System.Nullable<int> _max_months;
		
		private System.Nullable<int> _course_type;
		
		private System.Nullable<int> _cycle_exists;
		
		private string _cycle1;
		
		private string _cycle2;
		
		private System.Nullable<int> _markssheet;
		
		private System.Nullable<int> _attempts;
		
		private System.Nullable<int> _cutof_attendance;
		
		private System.Nullable<int> _grace_attendance;
		
		private System.Nullable<int> _leet;
		
		private System.Nullable<int> _StartRollNo;
		
		private System.Nullable<int> _EndRollNo;
		
		private System.Nullable<int> _Status;
		
		private System.Nullable<int> _ur_mid;
		
		private System.Nullable<int> _PAGE_ID;
		
		private System.Nullable<System.DateTime> _createddate;
		
		private System.Nullable<System.DateTime> _updateddate;
		
		private System.Nullable<int> _createdby;
		
		private System.Nullable<int> _updatedby;
		
		public PR_COURSE_SELECTResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pk_CourseID", DbType="Int NOT NULL")]
		public int Pk_CourseID
		{
			get
			{
				return this._Pk_CourseID;
			}
			set
			{
				if ((this._Pk_CourseID != value))
				{
					this._Pk_CourseID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CourseName", DbType="VarChar(50)")]
		public string CourseName
		{
			get
			{
				return this._CourseName;
			}
			set
			{
				if ((this._CourseName != value))
				{
					this._CourseName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_subbranch", DbType="Int")]
		public System.Nullable<int> subbranch
		{
			get
			{
				return this._subbranch;
			}
			set
			{
				if ((this._subbranch != value))
				{
					this._subbranch = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_enexam", DbType="Int")]
		public System.Nullable<int> enexam
		{
			get
			{
				return this._enexam;
			}
			set
			{
				if ((this._enexam != value))
				{
					this._enexam = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sem", DbType="Int")]
		public System.Nullable<int> sem
		{
			get
			{
				return this._sem;
			}
			set
			{
				if ((this._sem != value))
				{
					this._sem = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_years", DbType="Int")]
		public System.Nullable<int> years
		{
			get
			{
				return this._years;
			}
			set
			{
				if ((this._years != value))
				{
					this._years = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_months", DbType="Int")]
		public System.Nullable<int> months
		{
			get
			{
				return this._months;
			}
			set
			{
				if ((this._months != value))
				{
					this._months = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_papers", DbType="Int")]
		public System.Nullable<int> total_papers
		{
			get
			{
				return this._total_papers;
			}
			set
			{
				if ((this._total_papers != value))
				{
					this._total_papers = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_theory", DbType="Int")]
		public System.Nullable<int> theory
		{
			get
			{
				return this._theory;
			}
			set
			{
				if ((this._theory != value))
				{
					this._theory = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_practical", DbType="Int")]
		public System.Nullable<int> practical
		{
			get
			{
				return this._practical;
			}
			set
			{
				if ((this._practical != value))
				{
					this._practical = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_category", DbType="Int")]
		public System.Nullable<int> category
		{
			get
			{
				return this._category;
			}
			set
			{
				if ((this._category != value))
				{
					this._category = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_pattern", DbType="Int")]
		public System.Nullable<int> course_pattern
		{
			get
			{
				return this._course_pattern;
			}
			set
			{
				if ((this._course_pattern != value))
				{
					this._course_pattern = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_credit", DbType="Int")]
		public System.Nullable<int> credit
		{
			get
			{
				return this._credit;
			}
			set
			{
				if ((this._credit != value))
				{
					this._credit = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_university", DbType="Int")]
		public System.Nullable<int> university
		{
			get
			{
				return this._university;
			}
			set
			{
				if ((this._university != value))
				{
					this._university = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_college", DbType="Int")]
		public System.Nullable<int> college
		{
			get
			{
				return this._college;
			}
			set
			{
				if ((this._college != value))
				{
					this._college = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_description", DbType="VarChar(200)")]
		public string description
		{
			get
			{
				return this._description;
			}
			set
			{
				if ((this._description != value))
				{
					this._description = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_shortname", DbType="VarChar(50)")]
		public string shortname
		{
			get
			{
				return this._shortname;
			}
			set
			{
				if ((this._shortname != value))
				{
					this._shortname = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_years", DbType="Int")]
		public System.Nullable<int> max_years
		{
			get
			{
				return this._max_years;
			}
			set
			{
				if ((this._max_years != value))
				{
					this._max_years = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_max_months", DbType="Int")]
		public System.Nullable<int> max_months
		{
			get
			{
				return this._max_months;
			}
			set
			{
				if ((this._max_months != value))
				{
					this._max_months = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_course_type", DbType="Int")]
		public System.Nullable<int> course_type
		{
			get
			{
				return this._course_type;
			}
			set
			{
				if ((this._course_type != value))
				{
					this._course_type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycle_exists", DbType="Int")]
		public System.Nullable<int> cycle_exists
		{
			get
			{
				return this._cycle_exists;
			}
			set
			{
				if ((this._cycle_exists != value))
				{
					this._cycle_exists = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycle1", DbType="VarChar(50)")]
		public string cycle1
		{
			get
			{
				return this._cycle1;
			}
			set
			{
				if ((this._cycle1 != value))
				{
					this._cycle1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cycle2", DbType="VarChar(50)")]
		public string cycle2
		{
			get
			{
				return this._cycle2;
			}
			set
			{
				if ((this._cycle2 != value))
				{
					this._cycle2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_markssheet", DbType="Int")]
		public System.Nullable<int> markssheet
		{
			get
			{
				return this._markssheet;
			}
			set
			{
				if ((this._markssheet != value))
				{
					this._markssheet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_attempts", DbType="Int")]
		public System.Nullable<int> attempts
		{
			get
			{
				return this._attempts;
			}
			set
			{
				if ((this._attempts != value))
				{
					this._attempts = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cutof_attendance", DbType="Int")]
		public System.Nullable<int> cutof_attendance
		{
			get
			{
				return this._cutof_attendance;
			}
			set
			{
				if ((this._cutof_attendance != value))
				{
					this._cutof_attendance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_grace_attendance", DbType="Int")]
		public System.Nullable<int> grace_attendance
		{
			get
			{
				return this._grace_attendance;
			}
			set
			{
				if ((this._grace_attendance != value))
				{
					this._grace_attendance = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_leet", DbType="Int")]
		public System.Nullable<int> leet
		{
			get
			{
				return this._leet;
			}
			set
			{
				if ((this._leet != value))
				{
					this._leet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_StartRollNo", DbType="Int")]
		public System.Nullable<int> StartRollNo
		{
			get
			{
				return this._StartRollNo;
			}
			set
			{
				if ((this._StartRollNo != value))
				{
					this._StartRollNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EndRollNo", DbType="Int")]
		public System.Nullable<int> EndRollNo
		{
			get
			{
				return this._EndRollNo;
			}
			set
			{
				if ((this._EndRollNo != value))
				{
					this._EndRollNo = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Status", DbType="Int")]
		public System.Nullable<int> Status
		{
			get
			{
				return this._Status;
			}
			set
			{
				if ((this._Status != value))
				{
					this._Status = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ur_mid", DbType="Int")]
		public System.Nullable<int> ur_mid
		{
			get
			{
				return this._ur_mid;
			}
			set
			{
				if ((this._ur_mid != value))
				{
					this._ur_mid = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PAGE_ID", DbType="Int")]
		public System.Nullable<int> PAGE_ID
		{
			get
			{
				return this._PAGE_ID;
			}
			set
			{
				if ((this._PAGE_ID != value))
				{
					this._PAGE_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> createddate
		{
			get
			{
				return this._createddate;
			}
			set
			{
				if ((this._createddate != value))
				{
					this._createddate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updateddate", DbType="DateTime")]
		public System.Nullable<System.DateTime> updateddate
		{
			get
			{
				return this._updateddate;
			}
			set
			{
				if ((this._updateddate != value))
				{
					this._updateddate = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_createdby", DbType="Int")]
		public System.Nullable<int> createdby
		{
			get
			{
				return this._createdby;
			}
			set
			{
				if ((this._createdby != value))
				{
					this._createdby = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_updatedby", DbType="Int")]
		public System.Nullable<int> updatedby
		{
			get
			{
				return this._updatedby;
			}
			set
			{
				if ((this._updatedby != value))
				{
					this._updatedby = value;
				}
			}
		}
	}
	
	public partial class SP_GetStudentDetailsResult
	{
		
		private string _FK_CLGCODE;
		
		private string _HTNO;
		
		private string _FULLNAME;
		
		private string _FNAME;
		
		private string _FK_YEAR;
		
		private string _FK_SEM;
		
		private string _ORD;
		
		private string _EI;
		
		private string _CONVERT_SUBCODE;
		
		private string _SUBJECTNAME;
		
		private string _CREDITS;
		
		private string _VAL_MARKS;
		
		private string _INT_MARKS;
		
		private string _MOD1_MARKS;
		
		private string _MOD2_MARKS;
		
		private string _GRACE_MARKS;
		
		private string _GRACE_MARKS2;
		
		private string _FINAL_VAL_MARKS;
		
		private string _GRADEPOINT;
		
		private string _LETERGRADE;
		
		private string _RESULT;
		
		private string _FINALRESULT;
		
		private string _SGPA;
		
		public SP_GetStudentDetailsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_CLGCODE", DbType="NVarChar(255)")]
		public string FK_CLGCODE
		{
			get
			{
				return this._FK_CLGCODE;
			}
			set
			{
				if ((this._FK_CLGCODE != value))
				{
					this._FK_CLGCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTNO", DbType="NVarChar(255)")]
		public string HTNO
		{
			get
			{
				return this._HTNO;
			}
			set
			{
				if ((this._HTNO != value))
				{
					this._HTNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FULLNAME", DbType="NVarChar(255)")]
		public string FULLNAME
		{
			get
			{
				return this._FULLNAME;
			}
			set
			{
				if ((this._FULLNAME != value))
				{
					this._FULLNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FNAME", DbType="NVarChar(255)")]
		public string FNAME
		{
			get
			{
				return this._FNAME;
			}
			set
			{
				if ((this._FNAME != value))
				{
					this._FNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_YEAR", DbType="NVarChar(255)")]
		public string FK_YEAR
		{
			get
			{
				return this._FK_YEAR;
			}
			set
			{
				if ((this._FK_YEAR != value))
				{
					this._FK_YEAR = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FK_SEM", DbType="NVarChar(255)")]
		public string FK_SEM
		{
			get
			{
				return this._FK_SEM;
			}
			set
			{
				if ((this._FK_SEM != value))
				{
					this._FK_SEM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ORD", DbType="NVarChar(255)")]
		public string ORD
		{
			get
			{
				return this._ORD;
			}
			set
			{
				if ((this._ORD != value))
				{
					this._ORD = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EI", DbType="NVarChar(255)")]
		public string EI
		{
			get
			{
				return this._EI;
			}
			set
			{
				if ((this._EI != value))
				{
					this._EI = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CONVERT_SUBCODE", DbType="NVarChar(255)")]
		public string CONVERT_SUBCODE
		{
			get
			{
				return this._CONVERT_SUBCODE;
			}
			set
			{
				if ((this._CONVERT_SUBCODE != value))
				{
					this._CONVERT_SUBCODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SUBJECTNAME", DbType="NVarChar(255)")]
		public string SUBJECTNAME
		{
			get
			{
				return this._SUBJECTNAME;
			}
			set
			{
				if ((this._SUBJECTNAME != value))
				{
					this._SUBJECTNAME = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CREDITS", DbType="NVarChar(255)")]
		public string CREDITS
		{
			get
			{
				return this._CREDITS;
			}
			set
			{
				if ((this._CREDITS != value))
				{
					this._CREDITS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VAL_MARKS", DbType="NVarChar(255)")]
		public string VAL_MARKS
		{
			get
			{
				return this._VAL_MARKS;
			}
			set
			{
				if ((this._VAL_MARKS != value))
				{
					this._VAL_MARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_INT_MARKS", DbType="NVarChar(255)")]
		public string INT_MARKS
		{
			get
			{
				return this._INT_MARKS;
			}
			set
			{
				if ((this._INT_MARKS != value))
				{
					this._INT_MARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD1_MARKS", DbType="NVarChar(255)")]
		public string MOD1_MARKS
		{
			get
			{
				return this._MOD1_MARKS;
			}
			set
			{
				if ((this._MOD1_MARKS != value))
				{
					this._MOD1_MARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MOD2_MARKS", DbType="NVarChar(255)")]
		public string MOD2_MARKS
		{
			get
			{
				return this._MOD2_MARKS;
			}
			set
			{
				if ((this._MOD2_MARKS != value))
				{
					this._MOD2_MARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRACE_MARKS", DbType="NVarChar(255)")]
		public string GRACE_MARKS
		{
			get
			{
				return this._GRACE_MARKS;
			}
			set
			{
				if ((this._GRACE_MARKS != value))
				{
					this._GRACE_MARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRACE_MARKS2", DbType="NVarChar(255)")]
		public string GRACE_MARKS2
		{
			get
			{
				return this._GRACE_MARKS2;
			}
			set
			{
				if ((this._GRACE_MARKS2 != value))
				{
					this._GRACE_MARKS2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINAL_VAL_MARKS", DbType="NVarChar(255)")]
		public string FINAL_VAL_MARKS
		{
			get
			{
				return this._FINAL_VAL_MARKS;
			}
			set
			{
				if ((this._FINAL_VAL_MARKS != value))
				{
					this._FINAL_VAL_MARKS = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GRADEPOINT", DbType="NVarChar(255)")]
		public string GRADEPOINT
		{
			get
			{
				return this._GRADEPOINT;
			}
			set
			{
				if ((this._GRADEPOINT != value))
				{
					this._GRADEPOINT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LETERGRADE", DbType="NVarChar(255)")]
		public string LETERGRADE
		{
			get
			{
				return this._LETERGRADE;
			}
			set
			{
				if ((this._LETERGRADE != value))
				{
					this._LETERGRADE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RESULT", DbType="NVarChar(255)")]
		public string RESULT
		{
			get
			{
				return this._RESULT;
			}
			set
			{
				if ((this._RESULT != value))
				{
					this._RESULT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FINALRESULT", DbType="NVarChar(255)")]
		public string FINALRESULT
		{
			get
			{
				return this._FINALRESULT;
			}
			set
			{
				if ((this._FINALRESULT != value))
				{
					this._FINALRESULT = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGPA", DbType="NVarChar(255)")]
		public string SGPA
		{
			get
			{
				return this._SGPA;
			}
			set
			{
				if ((this._SGPA != value))
				{
					this._SGPA = value;
				}
			}
		}
	}
	
	public partial class get_ConsDataforTRResult
	{
		
		private string _CODE;
		
		private string _HTNO;
		
		private string _SEM;
		
		private string _P1;
		
		private string _M1;
		
		private string _S1;
		
		private string _R1;
		
		private string _A1;
		
		private string _P2;
		
		private string _M2;
		
		private string _S2;
		
		private string _R2;
		
		private string _A2;
		
		private string _P3;
		
		private string _M3;
		
		private string _S3;
		
		private string _R3;
		
		private string _A3;
		
		private string _P4;
		
		private string _M4;
		
		private string _S4;
		
		private string _R4;
		
		private string _A4;
		
		private string _P5;
		
		private string _M5;
		
		private string _S5;
		
		private string _R5;
		
		private string _A5;
		
		private string _P6;
		
		private string _M6;
		
		private string _S6;
		
		private string _R6;
		
		private string _A6;
		
		private string _P7;
		
		private string _M7;
		
		private string _S7;
		
		private string _R7;
		
		private string _A7;
		
		private string _P8;
		
		private string _M8;
		
		private string _S8;
		
		private string _R8;
		
		private string _A8;
		
		private string _P9;
		
		private string _M9;
		
		private string _S9;
		
		private string _R9;
		
		private string _A9;
		
		private string _P10;
		
		private string _M10;
		
		private string _S10;
		
		private string _R10;
		
		private string _A10;
		
		private string _RES;
		
		private string _SGPA;
		
		private string _EXAMMONT;
		
		public get_ConsDataforTRResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CODE", DbType="NVarChar(255)")]
		public string CODE
		{
			get
			{
				return this._CODE;
			}
			set
			{
				if ((this._CODE != value))
				{
					this._CODE = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HTNO", DbType="NVarChar(255)")]
		public string HTNO
		{
			get
			{
				return this._HTNO;
			}
			set
			{
				if ((this._HTNO != value))
				{
					this._HTNO = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEM", DbType="NVarChar(255)")]
		public string SEM
		{
			get
			{
				return this._SEM;
			}
			set
			{
				if ((this._SEM != value))
				{
					this._SEM = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P1", DbType="NVarChar(255)")]
		public string P1
		{
			get
			{
				return this._P1;
			}
			set
			{
				if ((this._P1 != value))
				{
					this._P1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M1", DbType="NVarChar(255)")]
		public string M1
		{
			get
			{
				return this._M1;
			}
			set
			{
				if ((this._M1 != value))
				{
					this._M1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S1", DbType="NVarChar(255)")]
		public string S1
		{
			get
			{
				return this._S1;
			}
			set
			{
				if ((this._S1 != value))
				{
					this._S1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R1", DbType="NVarChar(255)")]
		public string R1
		{
			get
			{
				return this._R1;
			}
			set
			{
				if ((this._R1 != value))
				{
					this._R1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A1", DbType="NVarChar(255)")]
		public string A1
		{
			get
			{
				return this._A1;
			}
			set
			{
				if ((this._A1 != value))
				{
					this._A1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P2", DbType="NVarChar(255)")]
		public string P2
		{
			get
			{
				return this._P2;
			}
			set
			{
				if ((this._P2 != value))
				{
					this._P2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M2", DbType="NVarChar(255)")]
		public string M2
		{
			get
			{
				return this._M2;
			}
			set
			{
				if ((this._M2 != value))
				{
					this._M2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S2", DbType="NVarChar(255)")]
		public string S2
		{
			get
			{
				return this._S2;
			}
			set
			{
				if ((this._S2 != value))
				{
					this._S2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R2", DbType="NVarChar(255)")]
		public string R2
		{
			get
			{
				return this._R2;
			}
			set
			{
				if ((this._R2 != value))
				{
					this._R2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A2", DbType="NVarChar(255)")]
		public string A2
		{
			get
			{
				return this._A2;
			}
			set
			{
				if ((this._A2 != value))
				{
					this._A2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P3", DbType="NVarChar(255)")]
		public string P3
		{
			get
			{
				return this._P3;
			}
			set
			{
				if ((this._P3 != value))
				{
					this._P3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M3", DbType="NVarChar(255)")]
		public string M3
		{
			get
			{
				return this._M3;
			}
			set
			{
				if ((this._M3 != value))
				{
					this._M3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S3", DbType="NVarChar(255)")]
		public string S3
		{
			get
			{
				return this._S3;
			}
			set
			{
				if ((this._S3 != value))
				{
					this._S3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R3", DbType="NVarChar(255)")]
		public string R3
		{
			get
			{
				return this._R3;
			}
			set
			{
				if ((this._R3 != value))
				{
					this._R3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A3", DbType="NVarChar(255)")]
		public string A3
		{
			get
			{
				return this._A3;
			}
			set
			{
				if ((this._A3 != value))
				{
					this._A3 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P4", DbType="NVarChar(255)")]
		public string P4
		{
			get
			{
				return this._P4;
			}
			set
			{
				if ((this._P4 != value))
				{
					this._P4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M4", DbType="NVarChar(255)")]
		public string M4
		{
			get
			{
				return this._M4;
			}
			set
			{
				if ((this._M4 != value))
				{
					this._M4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S4", DbType="NVarChar(255)")]
		public string S4
		{
			get
			{
				return this._S4;
			}
			set
			{
				if ((this._S4 != value))
				{
					this._S4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R4", DbType="NVarChar(255)")]
		public string R4
		{
			get
			{
				return this._R4;
			}
			set
			{
				if ((this._R4 != value))
				{
					this._R4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A4", DbType="NVarChar(255)")]
		public string A4
		{
			get
			{
				return this._A4;
			}
			set
			{
				if ((this._A4 != value))
				{
					this._A4 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P5", DbType="NVarChar(255)")]
		public string P5
		{
			get
			{
				return this._P5;
			}
			set
			{
				if ((this._P5 != value))
				{
					this._P5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M5", DbType="NVarChar(255)")]
		public string M5
		{
			get
			{
				return this._M5;
			}
			set
			{
				if ((this._M5 != value))
				{
					this._M5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S5", DbType="NVarChar(255)")]
		public string S5
		{
			get
			{
				return this._S5;
			}
			set
			{
				if ((this._S5 != value))
				{
					this._S5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R5", DbType="NVarChar(255)")]
		public string R5
		{
			get
			{
				return this._R5;
			}
			set
			{
				if ((this._R5 != value))
				{
					this._R5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A5", DbType="NVarChar(255)")]
		public string A5
		{
			get
			{
				return this._A5;
			}
			set
			{
				if ((this._A5 != value))
				{
					this._A5 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P6", DbType="NVarChar(255)")]
		public string P6
		{
			get
			{
				return this._P6;
			}
			set
			{
				if ((this._P6 != value))
				{
					this._P6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M6", DbType="NVarChar(255)")]
		public string M6
		{
			get
			{
				return this._M6;
			}
			set
			{
				if ((this._M6 != value))
				{
					this._M6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S6", DbType="NVarChar(255)")]
		public string S6
		{
			get
			{
				return this._S6;
			}
			set
			{
				if ((this._S6 != value))
				{
					this._S6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R6", DbType="NVarChar(255)")]
		public string R6
		{
			get
			{
				return this._R6;
			}
			set
			{
				if ((this._R6 != value))
				{
					this._R6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A6", DbType="NVarChar(255)")]
		public string A6
		{
			get
			{
				return this._A6;
			}
			set
			{
				if ((this._A6 != value))
				{
					this._A6 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P7", DbType="NVarChar(255)")]
		public string P7
		{
			get
			{
				return this._P7;
			}
			set
			{
				if ((this._P7 != value))
				{
					this._P7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M7", DbType="NVarChar(255)")]
		public string M7
		{
			get
			{
				return this._M7;
			}
			set
			{
				if ((this._M7 != value))
				{
					this._M7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S7", DbType="NVarChar(255)")]
		public string S7
		{
			get
			{
				return this._S7;
			}
			set
			{
				if ((this._S7 != value))
				{
					this._S7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R7", DbType="NVarChar(255)")]
		public string R7
		{
			get
			{
				return this._R7;
			}
			set
			{
				if ((this._R7 != value))
				{
					this._R7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A7", DbType="NVarChar(255)")]
		public string A7
		{
			get
			{
				return this._A7;
			}
			set
			{
				if ((this._A7 != value))
				{
					this._A7 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P8", DbType="NVarChar(255)")]
		public string P8
		{
			get
			{
				return this._P8;
			}
			set
			{
				if ((this._P8 != value))
				{
					this._P8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M8", DbType="NVarChar(255)")]
		public string M8
		{
			get
			{
				return this._M8;
			}
			set
			{
				if ((this._M8 != value))
				{
					this._M8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S8", DbType="NVarChar(255)")]
		public string S8
		{
			get
			{
				return this._S8;
			}
			set
			{
				if ((this._S8 != value))
				{
					this._S8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R8", DbType="NVarChar(255)")]
		public string R8
		{
			get
			{
				return this._R8;
			}
			set
			{
				if ((this._R8 != value))
				{
					this._R8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A8", DbType="NVarChar(255)")]
		public string A8
		{
			get
			{
				return this._A8;
			}
			set
			{
				if ((this._A8 != value))
				{
					this._A8 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P9", DbType="NVarChar(255)")]
		public string P9
		{
			get
			{
				return this._P9;
			}
			set
			{
				if ((this._P9 != value))
				{
					this._P9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M9", DbType="NVarChar(255)")]
		public string M9
		{
			get
			{
				return this._M9;
			}
			set
			{
				if ((this._M9 != value))
				{
					this._M9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S9", DbType="NVarChar(255)")]
		public string S9
		{
			get
			{
				return this._S9;
			}
			set
			{
				if ((this._S9 != value))
				{
					this._S9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R9", DbType="NVarChar(255)")]
		public string R9
		{
			get
			{
				return this._R9;
			}
			set
			{
				if ((this._R9 != value))
				{
					this._R9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A9", DbType="NVarChar(255)")]
		public string A9
		{
			get
			{
				return this._A9;
			}
			set
			{
				if ((this._A9 != value))
				{
					this._A9 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_P10", DbType="NVarChar(255)")]
		public string P10
		{
			get
			{
				return this._P10;
			}
			set
			{
				if ((this._P10 != value))
				{
					this._P10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_M10", DbType="NVarChar(255)")]
		public string M10
		{
			get
			{
				return this._M10;
			}
			set
			{
				if ((this._M10 != value))
				{
					this._M10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_S10", DbType="NVarChar(255)")]
		public string S10
		{
			get
			{
				return this._S10;
			}
			set
			{
				if ((this._S10 != value))
				{
					this._S10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_R10", DbType="NVarChar(255)")]
		public string R10
		{
			get
			{
				return this._R10;
			}
			set
			{
				if ((this._R10 != value))
				{
					this._R10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A10", DbType="NVarChar(255)")]
		public string A10
		{
			get
			{
				return this._A10;
			}
			set
			{
				if ((this._A10 != value))
				{
					this._A10 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RES", DbType="NVarChar(255)")]
		public string RES
		{
			get
			{
				return this._RES;
			}
			set
			{
				if ((this._RES != value))
				{
					this._RES = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SGPA", DbType="NVarChar(255)")]
		public string SGPA
		{
			get
			{
				return this._SGPA;
			}
			set
			{
				if ((this._SGPA != value))
				{
					this._SGPA = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_EXAMMONT", DbType="NVarChar(255)")]
		public string EXAMMONT
		{
			get
			{
				return this._EXAMMONT;
			}
			set
			{
				if ((this._EXAMMONT != value))
				{
					this._EXAMMONT = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
